# Generated by Django 5.2.8 on 2026-05-08 04:27

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoriaproducto',
            options={},
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={},
        ),
        migrations.AlterModelOptions(
            name='productor',
            options={},
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='disponibilidad',
            new_name='disponible',
        ),
        migrations.RemoveField(
            model_name='categoriaproducto',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='productor',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='productor',
            name='updated',
        ),
        migrations.AddField(
            model_name='productor',
            name='imagen',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='imagen'),
        ),
        migrations.AlterField(
            model_name='categoriaproducto',
            name='nombre',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='productor',
            name='nombre',
            field=models.CharField(max_length=120),
        ),
    ]
