# Generated by Django 5.2.8 on 2026-05-18 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0003_pedidoitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='ciudad',
        ),
        migrations.AddField(
            model_name='pedido',
            name='departamento',
            field=models.CharField(default='Tolima', max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedido',
            name='informacion_adicional',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='municipio',
            field=models.CharField(default='Tolima', max_length=120),
            preserve_default=False,
        ),
    ]
